name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install API dependencies
        run: |
          if [ -f api/requirements.txt ]; then pip install -r api/requirements.txt; fi
      - name: Python syntax check (API)
        run: |
          if [ -d api ]; then python -m compileall -q api; fi
